In [29]:
import pandas as pd
dframe = pd.read_csv("Downloads/archive (1)/ai_student_impact_dataset (1).csv")
print(dframe)
print(dframe.head())
dframe.shape
dframe.iloc[2:,2]
dframe.iloc[2:5,[0,1,2,5,9]]
dframe.set_index("Year_of_Study")
dframe.loc[0:2,['Student_ID','Year_of_Study']]

       Student_ID Major_Category Year_of_Study  Pre_Semester_GPA  \
0          100001     Humanities        Senior             2.418
1          100002        Medical        Junior             3.821
2          100003       Business      Freshman             3.398
3          100004       Business        Senior             3.789
4          100005           STEM     Sophomore             3.635
...           ...            ...           ...               ...
49995      149996       Business        Senior             2.899
49996      149997           STEM        Senior             2.870
49997      149998       Business        Senior             3.177
49998      149999       Business        Junior             3.398
49999      150000           Arts     Sophomore             3.242

       Weekly_GenAI_Hours           Primary_Use_Case Prompt_Engineering_Skill  \
0                   23.31       Copywriting/Drafting                 Beginner
1                    1.12                   Ideation                 Advanced
2                   21.26        Summarizing_Reading                 Beginner
3                    1.82       Copywriting/Drafting             Intermediate
4                    9.29  Debugging/Troubleshooting                 Advanced
...                   ...                        ...                      ...
49995               12.16       Copywriting/Drafting                 Beginner
49996                2.51       Copywriting/Drafting             Intermediate
49997               15.87        Summarizing_Reading                 Advanced
49998               19.91  Debugging/Troubleshooting             Intermediate
49999                3.30       Copywriting/Drafting                 Beginner

       Tool_Diversity  Paid_Subscription  Traditional_Study_Hours  \
0                   1               True                     8.13
1                   5              False                    16.65
2                   2              False                    10.35
3                   4              False                    15.23
4                   4              False                    12.55
...               ...                ...                      ...
49995               2              False                    13.36
49996               1              False                     4.67
49997               5               True                     3.92
49998               5              False                     7.10
49999               1              False                     3.93

       Perceived_AI_Dependency   Institutional_Policy  \
0                            5  Allowed_With_Citation
1                            3  Allowed_With_Citation
2                            5             Strict_Ban
3                            2  Allowed_With_Citation
4                            4  Allowed_With_Citation
...                        ...                    ...
49995                        2  Allowed_With_Citation
49996                        3    Actively_Encouraged
49997                        4  Allowed_With_Citation
49998                        5  Allowed_With_Citation
49999                        2  Allowed_With_Citation

       Anxiety_Level_During_Exams  Post_Semester_GPA  Skill_Retention_Score  \
0                               6              2.393                  86.44
1                               9              3.696                  69.39
2                               9              3.499                  73.93
3                               2              4.000                  63.58
4                               4              3.798                 100.00
...                           ...                ...                    ...
49995                           2              3.584                  66.16
49996                           3              3.096                  81.62
49997                           5              3.605                  97.21
49998                           3              3.527                  84.12
49999                           6              3.261                  76.16

      Burnout_Risk_Level
0                   High
1                    Low
2                 Medium
3                 Medium
4                 Medium
...                  ...
49995               High
49996             Medium
49997               High
49998             Medium
49999                Low

[50000 rows x 16 columns]
   Student_ID Major_Category Year_of_Study  Pre_Semester_GPA  \
0      100001     Humanities        Senior             2.418
1      100002        Medical        Junior             3.821
2      100003       Business      Freshman             3.398
3      100004       Business        Senior             3.789
4      100005           STEM     Sophomore             3.635

   Weekly_GenAI_Hours           Primary_Use_Case Prompt_Engineering_Skill  \
0               23.31       Copywriting/Drafting                 Beginner
1                1.12                   Ideation                 Advanced
2               21.26        Summarizing_Reading                 Beginner
3                1.82       Copywriting/Drafting             Intermediate
4                9.29  Debugging/Troubleshooting                 Advanced

   Tool_Diversity  Paid_Subscription  Traditional_Study_Hours  \
0               1               True                     8.13
1               5              False                    16.65
2               2              False                    10.35
3               4              False                    15.23
4               4              False                    12.55

   Perceived_AI_Dependency   Institutional_Policy  Anxiety_Level_During_Exams  \
0                        5  Allowed_With_Citation                           6
1                        3  Allowed_With_Citation                           9
2                        5             Strict_Ban                           9
3                        2  Allowed_With_Citation                           2
4                        4  Allowed_With_Citation                           4

   Post_Semester_GPA  Skill_Retention_Score Burnout_Risk_Level
0              2.393                  86.44               High
1              3.696                  69.39                Low
2              3.499                  73.93             Medium
3              4.000                  63.58             Medium
4              3.798                 100.00             Medium

   Student_ID Year_of_Study
0      100001        Senior
1      100002        Junior
2      100003      Freshman

In [12]:
import pandas as pd
dframe = pd.read_csv("Downloads/archive (1)/ai_student_impact_dataset (1).csv")
dframe.loc[:,['Student_ID','Pre_Semester_GPA','Year_of_Study']]
dframe.columns

Index(['Student_ID', 'Major_Category', 'Year_of_Study', 'Pre_Semester_GPA',
       'Weekly_GenAI_Hours', 'Primary_Use_Case', 'Prompt_Engineering_Skill',
       'Tool_Diversity', 'Paid_Subscription', 'Traditional_Study_Hours',
       'Perceived_AI_Dependency', 'Institutional_Policy',
       'Anxiety_Level_During_Exams', 'Post_Semester_GPA',
       'Skill_Retention_Score', 'Burnout_Risk_Level'],
      dtype='object')

In [13]:
import pandas as pd
dframe = pd.read_csv("Downloads/archive (1)/ai_student_impact_dataset (1).csv")
dframe.loc[:,'Year_of_Study']==2008

0        False
1        False
2        False
3        False
4        False
         ...
49995    False
49996    False
49997    False
49998    False
49999    False
Name: Year_of_Study, Length: 50000, dtype: bool

In [26]:
import pandas as pd
dframe = pd.read_csv("Downloads/archive (1)/ai_student_impact_dataset (1).csv")
filt=dframe['Burnout_Risk_Level']== 'Low'
dframe.loc[filt].head
dframe.loc[filt].sort_index().head()
wdf=dframe.loc[filt].sort_index(ascending=False).head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low
49992,149993,Business,Graduate,2.829,2.59,Debugging/Troubleshooting,Advanced,3,True,7.54,1,Allowed_With_Citation,4,3.176,84.04,Low
49988,149989,STEM,Sophomore,2.058,3.32,Debugging/Troubleshooting,Beginner,1,False,6.34,4,Actively_Encouraged,4,2.147,68.75,Low
49987,149988,Humanities,Junior,2.980,0.50,Direct_Answer_Generation,Intermediate,2,False,16.07,4,Allowed_With_Citation,2,3.568,86.06,Low
49985,149986,Humanities,Sophomore,3.661,1.91,Copywriting/Drafting,Beginner,3,True,14.19,3,Actively_Encouraged,2,3.910,84.82,Low